### ISSUE TITLE
Implementing a Beacon in RPi3A+

### ISSUE THREAD

**Issue by guillego** [blue-heron/blue_heron#102]
I'm building a simple Beacon emitter (in Nerves) for RPI 3A+ and I'm using `{:blue_heron_transport_uart, "~> 0.1.3"}`  and  `{:blue_heron, "~> 0.3.0"}`.

Not sure if I need to load any specific overlays onto the raspberry pi config though.

I get this error when initializing the Beacon server:

```
14:24:06.052 [info] Application my_device exited: MyDevice.Application.start(:normal, []) returned an error: shutdown: failed to start child: MyDevice.Bluetooth.Beacon
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, :enoent}
            (blue_heron_transport_uart 0.1.3) lib/blue_heron_transport_uart.ex:50: BlueHeronTransportUART.init/1
            (stdlib 5.0) gen_server.erl:962: :gen_server.init_it/2
            (stdlib 5.0) gen_server.erl:917: :gen_server.init_it/6
            (stdlib 5.0) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

According to the [README](https://github.com/blue-heron/blue_heron/blob/main/README.md) the BT chipset of the RPI3A+ is not supported yet due to #21 but it was opened a long time ago so I'm not sure where things stand here.

Could it be related?

These are my modules:

Here are the modules, I believe the error comes up from this line in the `init/1` of the Beacon module:
`{:ok, ctx} = BlueHeron.transport(transport_config)`

```
defmodule MyDevice.Bluetooth.GattServer do
  @behaviour BlueHeron.GATT.Server
  require Logger

  @server_name "Beacon Server"

  @impl BlueHeron.GATT.Server
  def profile() do
    [
      BlueHeron.GATT.Service.new(%{
        id: :gap,
        type: 0x1800,
        characteristics: [
          BlueHeron.GATT.Characteristic.new(%{
            id: {:gap, :device_name},
            type: 0x2A00,  # This is the standard UUID for "Device Name" characteristic.
            properties: 0b0000010  # Read-only property.
          })
        ]
      })
    ]
  end

  @impl BlueHeron.GATT.Server
  def read({:gap, :device_name}), do: @server_name

  @impl BlueHeron.GATT.Server
  def write(_tuple, value) do
    Logger.info("Received a write attempt with value: #{value}")
  end
end
```

```
defmodule MyDevice.Bluetooth.Beacon do
  use GenServer

  alias BlueHeron.Peripheral
  alias BlueHeron.DataType.ManufacturerData.Apple
  alias BlueHeron.HCI.Command.ControllerAndBaseband.WriteLocalName

  require Logger

  @init_commands [%WriteLocalName{name: "Guille's Beacon"}]

  @default_uart_config %{
    device: "ttyACM0",
    uart_opts: [speed: 115_200],
    init_commands: @init_commands
  }

  # Config for iBeacon advertising parameters
  @advertising_params %{
    # Equivalent to 100ms
    interval_min: 160,
    # Equivalent to 100ms
    interval_max: 160,
    type: :connectable_undirected,
    own_address_type: :public,
    # All channels: 37, 38, and 39
    channel_map: 7,
    filter_policy: :allow_any
  }

  def start_link(_config) do
    {:ok, config} = Application.fetch_env(:my_device, :bluetooth)
    Logger.info(inspect(config))

    GenServer.start_link(__MODULE__, config)
  end

  @impl GenServer
  def init(config) do
    # Initialize the GATT Server
    gatt_server = MyDevice.Bluetooth.GattServer

    transport_config = struct(BlueHeronTransportUART, @default_uart_config)
    # Initialize transport context
    {:ok, ctx} = BlueHeron.transport(transport_config)

    # Initialize the BlueHeron.Peripheral
    {:ok, peripheral_pid} = Peripheral.start_link(ctx, gatt_server)

    # Serialize the iBeacon payload
    payload =
      Apple.serialize(
        {"iBeacon",
         %{
           major: config[:major],
           minor: config[:minor],
           tx_power: config[:tx_power],
           uuid: config[:uuid]
         }}
      )

    # Set advertising info in Peripheral
    Peripheral.set_advertising_parameters(peripheral_pid, @advertising_params)

    Peripheral.set_advertising_data(peripheral_pid, payload)

    # Schedule advertising
    schedule_advertising()

    {:ok, %{peripheral_pid: peripheral_pid, gatt_server: gatt_server, config: config}}
  end

  defp schedule_advertising() do
    Process.send_after(self(), :start_advertising, 1_000)
  end

  @impl GenServer
  def handle_info(:start_advertising, state) do
    # Start advertising for 9 sec
    Peripheral.start_advertising(state.peripheral_pid)
    Process.send_after(self(), :stop_advertising, 9_000)

    {:noreply, state}
  end

  def handle_info(:stop_advertising, state) do
    # Stop advertising
    Peripheral.stop_advertising(state.peripheral_pid)

    # Schedule the next advertising
    schedule_advertising()

    {:noreply, state}
  end
end
```

**Comment by trarbr** [comment]
Hi @guillego 👋  Thank you for the detailed issue.

You are right that the issue occurs when you call `{:ok, ctx} = BlueHeron.transport(transport_config)`. And the error says that it cannot open the UART device `ttyACM0`.

Unfortunately, I do not have an RPI3A+ for testing, but I also believe that it **should** work. But it might require fiddling a little with your /boot/config.txt file. Unfortunately I don't have time to write a proper response now, but:

If you have this in your /boot/config.txt:
```
enable_uart=1
dtoverlay=miniuart-bt
```

I think the right device to use is `ttyS0`.

If you have access to a shell on your Nerves device you can run `Circuits.UART.enumerate` to list the available UARTs.

**Comment by guillego** [comment]
Hej Troels! Mange tak that helped a lot!! I had those lines set up in my config.txt but just the simple switch to using `ttyS0` got rid of the error!

I still haven't been able to detect my nerves beacon but at least I don't have any init errors anymore! I'll have to keep exploring.

This is my current implementation in case there's anything obvious to make it work:

```elixir

defmodule MyDevice.Bluetooth.Beacon do
  use GenServer

  alias BlueHeron.Peripheral
  alias BlueHeron.DataType.ManufacturerData.Apple
  alias BlueHeron.HCI.Command.ControllerAndBaseband.WriteLocalName

  require Logger

  @init_commands [%WriteLocalName{name: "MyDevice Beacon"}]

  @default_uart_config %{
    device: "ttyS0",        # "ttyAMA0" "ttyACM0"
    uart_opts: [speed: 115_200],
    init_commands: @init_commands
  }

  # Config for iBeacon advertising parameters
  @advertising_params %{
    advertising_interval_min: 0x0190,     # 0.25 sec
    advertising_interval_max: 0x04B0,     # 0.75 sec
    advertising_type: 0x02,               # 0x02 is for scannable undirected advertising.
    own_address_type: 0x00,               # 0x00 is for a public address.
    peer_address_type: 0x00,              # 0x00 is for a public address.
    peer_address: 0x000000000000,         # Address of the peer device???? 
    advertising_channel_map: 0x07,        # 7 for all channels (37, 38, 39)
    advertising_filter_policy: 0x00       # 0x00 allows any device to scan and connect.
  }

  def start_link(_config) do
    {:ok, config} = Application.fetch_env(:my_device, :bluetooth)
    Logger.info(inspect(config))

    GenServer.start_link(__MODULE__, config)
  end

  @impl GenServer
  def init(config) do
    # Initialize the GATT Server
    gatt_server = MyDevice.Bluetooth.GattServer

    transport_config = struct(BlueHeronTransportUART, @default_uart_config)

    # Initialize transport context
    {:ok, ctx} = BlueHeron.transport(transport_config)

    {:ok, peripheral_pid} = Peripheral.start_link(ctx, gatt_server)

    uuid_int = config[:uuid]
                |> UUID.string_to_binary!()
                |> :binary.decode_unsigned()

    Logger.info("Serialized UUID: #{uuid_int}")

    # Serialize the iBeacon payload
    {:ok, payload} =
      Apple.serialize(
        {"iBeacon",
         %{
           major: config[:major],
           minor: config[:minor],
           tx_power: config[:tx_power],
           uuid: uuid_int
         }}
      )
    Logger.info("Setting up iBeacon advertising")
    Logger.info(inspect(payload))

    # Set advertising parameters
    Peripheral.set_advertising_parameters(peripheral_pid, @advertising_params)

    # Set advertising data with the payload
    Peripheral.set_advertising_data(peripheral_pid, payload)

    # Schedule the first advertising event immediately
    Process.send_after(self(), :start_advertising, 100)

    {:ok, %{peripheral_pid: peripheral_pid, gatt_server: gatt_server, config: config}}
  end

  @impl GenServer
  def handle_info(:start_advertising, state) do
    Logger.info("Starting advertising")
    Peripheral.start_advertising(state.peripheral_pid)

    # Advertise for the designated period (120 sec)
    Process.send_after(self(), :stop_advertising, state.config[:advertising_period])

    {:noreply, state}
  end

  def handle_info(:stop_advertising, state) do
    Logger.info("Stopping advertising")
    Peripheral.stop_advertising(state.peripheral_pid)

    # Schedule the next advertising
    Process.send_after(self(), :start_advertising, 1_000)

    {:noreply, state}
  end

end
```

And the advertising payload is:
`<<2, 21, 146, 224, 36, 79, 158, 197, 68, 114, 189, 230, 244, 151, 88, 107, 228, 112, 0, 1, 0, 2, 207>>`

Not sure if my advertising params are correct, I set it to scannable and undirected from what I could gather in the spec, but perhaps it's not what works in iBeacon.

**Comment by guillego** [comment]
Here's a minimal working example project in case that's easier!

https://github.com/guillego/nerves_beacon

**Comment by guillego** [comment]
Everything seems ok from the hci_dump (it's an `.pklg` file but github didn't allow it)
[nerves_beacon00_hcidump.txt](https://github.com/blue-heron/blue_heron/files/12641233/nerves_beacon00_hcidump.txt) but I'm not well versed in this.

**Comment by trarbr** [comment]
I don't have any knowledge about the specifics of iBeacon, but I can probably take a look at it in the next couple of days. Thank you for providing the hci_dump, that will probably be helpful.

What app/tool are you using to try to discover your beacon? 

I usually use the "nRF Connect for Mobile" app to debug these kinds of things. It gives a pretty "raw" look at the Bluetooth traffic around you. Maybe you can use that to check if your beacon appears? And if it does not, try going back to default advertising parameters, and see if you can see your beacon in nRF Connect? 

If we can establish that your device is sending out Bluetooth advertising packets, then it should be "just" a problem of finding the right advertising parameters for the iBeacon.

**Comment by guillego** [comment]
This was incredibly helpful @trarbr!

I was using a Beacon specific app for detecting it and I couldn't find it. Through the _nRF Connect_ app, I was able to see that the beacon was being transmitted, but that the payload was wrong!

I was setting it to this:
<<2, 21, 146, 224, 36, 79, 158, 197, 68, 114, 189, 230, 244, 151, 88, 107, 228, 112, 0, 1, 0, 2, 207>>

Which is what the `BlueHeron.DataType.ManufacturerData.Apple.serialize()` function returns, but then I dug a bit deeper into the standard and figured that I was missing out some preamble fields like flags, lengths, etc. I added the preamble and voilá! Everything seems to be working well now!

![IMAGE 2023-09-17 12:00:00](https://github.com/blue-heron/blue_heron/assets/864315/ff8c9fe8-f140-4dea-b69a-48caaf84a92c)

![IMAGE 2023-09-17 12:00:22](https://github.com/blue-heron/blue_heron/assets/864315/65bdc8ba-bcb6-4d43-aec0-642a9d50f204)



This issue can be closed I think! I'll keep the implementation in https://github.com/guillego/nerves_beacon but if you think it's useful I'm more than happy to contribute it to the examples section.

Also not sure if we should add some extra function to the BlueHeron code to provide the extra preamble to the manufacturer data that the iBeacon payload needs! Perhaps I can open a PR and you or some of the other maintainers can review it?

**Comment by trarbr** [comment]
Hurray 🎉 That's great news!

You are very welcome to consider how BlueHeron could be improved for this use case. I guess the main issue might be the lack of documentation for the BlueHeron.Peripheral module? It could at least drop some pointers about what advertising data is, and how to construct it with length, type, data, etc. Other ideas for improvements are also welcome 😄

You are most welcome to cook up a PR when you think of a good approach.
