### ISSUE TITLE
Using MacBooks included blueooth

### ISSUE THREAD

**Issue by philipgiuliani** [blue-heron/blue_heron#65]
Hi, i tried to get running by using the integrated bluetooth chip in the Mac, but couldn't get it to work. Is it supported? If so, which transport do I have to use?

**Comment by ConnorRigby** [comment]
as far as i know, no one has tried this. It's possible that the UART transport could work, but i doubt that Mac OS will let you access it directly. 
The easiest method to test Blue Heron on a desktop is likely something like [this](https://www.amazon.com/EDUP-Wireless-Desktop-Compatible-10-6-10-11/dp/B0827LG8L2) or anything else that uses the `EDUP EP-AC1681` chipset.

**Comment by philipgiuliani** [comment]
Ok, thanks for the info!

PS: blue_heron_transport_uart and blue_heron_transport_usb are locked to blue_heron 0.1.0. They cannot be used with blue_heron 0.2.0, is that intentional? ☺️
